### ISSUE TITLE
Safari initial render issue

### ISSUE THREAD

**Issue by vwall** [yjs/y-prosemirror#17] opened 2020-05-07 02:05 UTC
Running into a strange issue with Safari.  Chrome and Firefox are fine.  

On a hard refresh the doc remains blank but other connected browsers display this initial render correctly.  If i navigate to another doc Safari behaves correctly.  

Every once in a while i can get Safari to display the initial content if it originated from Safari (super rare though). 

I've noticed in the sync-plugin.js line 146 ``changedInitialContent`` is always ``false`` ``view.state.doc.content.size`` is always ``2`` and ``emptySize`` is always ``2`` where chrome will be the same until if finally syncs.

https://github.com/yjs/y-prosemirror/blob/master/src/plugins/sync-plugin.js#L146

**Comment by vwall** [comment] 2020-05-08 18:05
Looks like https://github.com/yjs/yjs/commit/4b08c67e06e351d6af5e624821f52b7ae54c39c1 this commit fixes it!  Thank you!!!!

**Comment by dmonad** [comment] 2020-05-08 20:27
Awesome, I was just going to ask ^^

**Comment by vwall** [comment] 2020-05-14 20:43
@dmonad I'm not 100% sure if this issue is back.  But we are now seeing the same behavior in Chrome and Safari.

**Comment by dmonad** [comment] 2020-05-15 13:30
Can you make sure that you are using the latest version of lib0? 

Safari's TextEncoder has an issue with utf8 encoding. How do you reproduce this issue in Chrome and Safari? 

In one of the "incomplete" documents,  can you log `doc.share`. Does it have duplicate keys?

**Comment by vwall** [comment] 2020-05-15 20:13
So I'm not 100% convinced this is the same problem.  This issue seems to only happen when the user is connected to the same doc multiple times. It throws this error

```Cannot read property 'matchesNode' of null``` from https://github.com/yjs/y-prosemirror/blob/master/src/plugins/sync-plugin.js#L244

**Comment by dmonad** [comment] 2020-05-15 21:02
Then there seems to be something wrong with the initial transaction. Can you please log some more information?
• The transaction changes.
• Maybe the output of `view.state.apply(tr)`, if that even computes.
• The full error stack

I can't really help with this issue if I can't reproduce it.

**Comment by vwall** [comment] 2020-05-15 21:05
Yea i totally understand.  I can't actually reproduce it either.  It's a person on the team that runs into it at will.  I'll see what i can give ya.

**Comment by dmonad** [comment] 2020-06-19 18:43
Gonna close this for now. Please reopen if you can reproduce it and make sure to specify which version of lib0 you are using.

**Closed by dmonad** 2020-06-19 18:43 UTC
